/**
 * Windows autostart backend — HKCU Run key + hidden VBS shim.
 *
 * Registry key: HKCU\Software\Microsoft\Windows\CurrentVersion\Run
 * Value name:   crontick-daemon  (or CRONTICK_AUTOSTART_TEST_VALUE for tests)
 * Value data:   wscript.exe "<dataDir>\autostart\crontick-daemon.vbs"
 *
 * The VBS shim launches crontick-daemon via `cmd /c` with window style 0 (hidden).
 */
import { spawnSync } from 'node:child_process';
import {
  writeFileSync,
  existsSync,
  unlinkSync,
  mkdirSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { autostartDir } from '../paths.js';
import type { AutostartStatus } from './index.js';

const RUN_KEY = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';

function getValueName(): string {
  return process.env['CRONTICK_AUTOSTART_TEST_VALUE'] ?? 'crontick-daemon';
}

function getVbsPath(): string {
  return join(autostartDir(), 'crontick-daemon.vbs');
}

/**
 * Locate the absolute path to the crontick-daemon binary/cmd wrapper.
 * Prefers `where.exe` detection so PATH changes don't break the shim.
 * CRONTICK_DAEMON_BINARY env var overrides detection (useful in CI/tests).
 */
function findDaemonBinary(): string | null {
  // 0. Test / CI override
  const override = process.env['CRONTICK_DAEMON_BINARY'];
  if (override) return override;

  // 1. Try where.exe
  const whereResult = spawnSync('where.exe', ['crontick-daemon'], {
    encoding: 'utf-8',
    timeout: 5_000,
    windowsHide: true,
  });
  if (whereResult.status === 0 && whereResult.stdout.trim()) {
    const first = whereResult.stdout.trim().split(/[\r\n]+/)[0]?.trim();
    if (first) return first;
  }

  // 2. Fallback: look in the same directory as the Node.js executable
  const nodeDir = dirname(process.execPath);
  for (const candidate of ['crontick-daemon.cmd', 'crontick-daemon']) {
    const p = join(nodeDir, candidate);
    if (existsSync(p)) return p;
  }

  return null;
}

function buildVbsContent(daemonPath: string): string {
  // Remove any double-quotes in path (shouldn't exist in valid Win paths)
  const safePath = daemonPath.replace(/"/g, '');
  return [
    "' crontick-daemon autostart shim — generated by crontick autostart install",
    "' Do not edit manually. Run: crontick autostart install to regenerate.",
    'Set WshShell = CreateObject("WScript.Shell")',
    `WshShell.Run "cmd /c ""${safePath}""", 0, False`,
    '',
  ].join('\r\n');
}

function regQuery(valueName: string): string | null {
  const result = spawnSync(
    'reg',
    ['query', RUN_KEY, '/v', valueName],
    { encoding: 'utf-8', timeout: 5_000, windowsHide: true },
  );
  if (result.status !== 0 || !result.stdout) return null;
  // Output format: "    valueName    REG_SZ    <data>"
  const match = result.stdout.match(/REG_SZ\s+(.+)/i);
  return match?.[1]?.trim() ?? null;
}

function regWrite(valueName: string, data: string): void {
  const result = spawnSync(
    'reg',
    ['add', RUN_KEY, '/v', valueName, '/t', 'REG_SZ', '/d', data, '/f'],
    { encoding: 'utf-8', timeout: 5_000, windowsHide: true },
  );
  if (result.status !== 0) {
    throw new Error(
      `reg.exe add failed (exit ${result.status ?? '?'}): ${result.stderr?.trim() ?? 'unknown error'}`,
    );
  }
}

function regDelete(valueName: string): void {
  spawnSync(
    'reg',
    ['delete', RUN_KEY, '/v', valueName, '/f'],
    { encoding: 'utf-8', timeout: 5_000, windowsHide: true },
  );
  // Ignore errors (value may not exist)
}

export class Win32Autostart {
  async install(): Promise<{ ok: true }> {
    const daemonPath = findDaemonBinary();
    if (!daemonPath) {
      throw new Error(
        'crontick-daemon binary not found. Ensure crontick is installed globally: npm i -g crontick',
      );
    }

    const vbsPath = getVbsPath();
    const valueName = getValueName();

    // Ensure directory and write VBS shim
    mkdirSync(autostartDir(), { recursive: true });
    writeFileSync(vbsPath, buildVbsContent(daemonPath), 'utf-8');

    // Idempotent: remove previous value before writing
    regDelete(valueName);
    regWrite(valueName, `wscript.exe "${vbsPath}"`);

    return { ok: true };
  }

  async remove(): Promise<{ ok: true }> {
    const valueName = getValueName();
    regDelete(valueName);

    // Remove VBS shim if it exists
    const vbsPath = getVbsPath();
    if (existsSync(vbsPath)) {
      try { unlinkSync(vbsPath); } catch { /* ignore */ }
    }

    return { ok: true };
  }

  async status(): Promise<AutostartStatus> {
    const valueName = getValueName();
    const data = regQuery(valueName);
    const installed = data !== null;
    return {
      installed,
      backend: 'win32',
      details: installed
        ? { registryValue: valueName, registryData: data, vbsPath: getVbsPath() }
        : { registryValue: valueName },
    };
  }
}
