/**
 * Windows autostart backend — HKCU Run key + hidden VBS shim.
 *
 * Registry key: HKCU\Software\Microsoft\Windows\CurrentVersion\Run
 * Value name:   crontick-daemon  (or CRONTICK_AUTOSTART_TEST_VALUE for tests)
 * Value data:   wscript.exe "<dataDir>\autostart\crontick-daemon.vbs"
 *
 * The VBS shim launches crontick-daemon via `cmd /c` with window style 0 (hidden).
 */
import { spawnSync } from 'node:child_process';
import {
  writeFileSync,
  existsSync,
  unlinkSync,
  mkdirSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { autostartDir } from '../paths.js';
import type { AutostartStatus } from './index.js';

const RUN_KEY = 'Software\\Microsoft\\Windows\\CurrentVersion\\Run';
const RUN_KEY_DISPLAY = `HKCU\\${RUN_KEY}`;

type RegistryValue = {
  readonly name: string;
  readonly type: string;
  readonly data: string | number;
};

type RegistryJsModule = {
  readonly HKEY: { readonly HKEY_CURRENT_USER: string };
  readonly RegistryValueType: { readonly REG_SZ: string };
  readonly setValue: (
    key: string,
    subkey: string,
    valueName: string,
    valueType: string,
    valueData: string,
  ) => boolean;
  readonly createKey?: (key: string, subkey: string) => boolean;
  readonly deleteValue?: (key: string, subkey: string, valueName: string) => boolean;
  readonly enumerateValues: (key: string, subkey: string) => ReadonlyArray<RegistryValue>;
};

let registryJs: RegistryJsModule | null = null;

type RegistryGlobal = typeof globalThis & { __crontickRegistryJs?: RegistryJsModule };

async function loadRegistryJs(): Promise<RegistryJsModule> {
  const testRegistryJs = (globalThis as RegistryGlobal).__crontickRegistryJs;
  if (testRegistryJs) return testRegistryJs;
  if (!registryJs) {
    const imported = await import('registry-js') as RegistryJsModule & { default?: RegistryJsModule };
    registryJs = imported.default ?? imported;
  }
  return registryJs;
}

function getValueName(): string {
  return process.env['CRONTICK_AUTOSTART_TEST_VALUE'] ?? 'crontick-daemon';
}

function getVbsPath(): string {
  return join(autostartDir(), 'crontick-daemon.vbs');
}

/**
 * Locate the absolute path to the crontick-daemon binary/cmd wrapper.
 * Prefers `where.exe` detection so PATH changes don't break the shim.
 * CRONTICK_DAEMON_BINARY env var overrides detection (useful in CI/tests).
 */
function findDaemonBinary(): string | null {
  // 0. Test / CI override
  const override = process.env['CRONTICK_DAEMON_BINARY'];
  if (override) return override;

  // 1. Try where.exe
  const whereResult = spawnSync('where.exe', ['crontick-daemon'], {
    encoding: 'utf-8',
    timeout: 5_000,
    windowsHide: true,
  });
  if (whereResult.status === 0 && whereResult.stdout.trim()) {
    const first = whereResult.stdout.trim().split(/[\r\n]+/)[0]?.trim();
    if (first) return first;
  }

  // 2. Fallback: look in the same directory as the Node.js executable
  const nodeDir = dirname(process.execPath);
  for (const candidate of ['crontick-daemon.cmd', 'crontick-daemon']) {
    const p = join(nodeDir, candidate);
    if (existsSync(p)) return p;
  }

  return null;
}

function buildVbsContent(daemonPath: string): string {
  // Remove any double-quotes in path (shouldn't exist in valid Win paths)
  const safePath = daemonPath.replace(/"/g, '');
  return [
    "' crontick-daemon autostart shim — generated by crontick autostart install",
    "' Do not edit manually. Run: crontick autostart install to regenerate.",
    'Set WshShell = CreateObject("WScript.Shell")',
    `WshShell.Run "cmd /c ""${safePath}""", 0, False`,
    '',
  ].join('\r\n');
}

function getRunKey(registry: RegistryJsModule): string {
  return registry.HKEY.HKEY_CURRENT_USER;
}

async function registryQuery(valueName: string): Promise<string | null> {
  const registry = await loadRegistryJs();
  let values: ReadonlyArray<RegistryValue>;
  try {
    values = registry.enumerateValues(getRunKey(registry), RUN_KEY);
  } catch (error) {
    if (isMissingRegistryValueError(error)) return null;
    throw error;
  }
  const entry = values.find((value) => value.name.toLowerCase() === valueName.toLowerCase());
  return typeof entry?.data === 'string' ? entry.data : null;
}

async function registryWrite(valueName: string, data: string): Promise<void> {
  const registry = await loadRegistryJs();
  registry.createKey?.(getRunKey(registry), RUN_KEY);
  const ok = registry.setValue(
    getRunKey(registry),
    RUN_KEY,
    valueName,
    registry.RegistryValueType.REG_SZ,
    data,
  );
  if (!ok) {
    throw new Error(`registry-js setValue failed for ${RUN_KEY_DISPLAY}\\${valueName}`);
  }
}

function isMissingRegistryValueError(error: unknown): boolean {
  if (!(error instanceof Error)) return false;
  return /not found|cannot find|file not found|ERROR_FILE_NOT_FOUND|ENOENT/i.test(error.message);
}

function quotePowerShellLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function deleteWithPowerShellRegistryApi(valueName: string): void {
  const literalPath = `Registry::HKEY_CURRENT_USER\\${RUN_KEY}`;
  const script = [
    'Remove-ItemProperty',
    '-LiteralPath', quotePowerShellLiteral(literalPath),
    '-Name', quotePowerShellLiteral(valueName),
    '-ErrorAction', 'SilentlyContinue',
  ].join(' ');
  const result = spawnSync(
    'powershell.exe',
    ['-NoProfile', '-NonInteractive', '-Command', script],
    { encoding: 'utf-8', timeout: 5_000, windowsHide: true },
  );
  if (result.status !== 0) {
    throw new Error(
      `PowerShell registry delete failed (exit ${result.status ?? '?'}): ${result.stderr?.trim() ?? 'unknown error'}`,
    );
  }
}

async function registryDelete(valueName: string): Promise<void> {
  const registry = await loadRegistryJs();
  if (typeof registry.deleteValue !== 'function') {
    deleteWithPowerShellRegistryApi(valueName);
    return;
  }

  try {
    registry.deleteValue(getRunKey(registry), RUN_KEY, valueName);
  } catch (error) {
    if (!isMissingRegistryValueError(error)) throw error;
  }
}

export class Win32Autostart {
  async install(): Promise<{ ok: true }> {
    const daemonPath = findDaemonBinary();
    if (!daemonPath) {
      throw new Error(
        'crontick-daemon binary not found. Ensure crontick is installed globally: npm i -g crontick',
      );
    }

    const vbsPath = getVbsPath();
    const valueName = getValueName();

    // Ensure directory and write VBS shim
    mkdirSync(autostartDir(), { recursive: true });
    writeFileSync(vbsPath, buildVbsContent(daemonPath), 'utf-8');

    await registryWrite(valueName, `wscript.exe "${vbsPath}"`);

    return { ok: true };
  }

  async remove(): Promise<{ ok: true }> {
    const valueName = getValueName();
    await registryDelete(valueName);

    // Remove VBS shim if it exists
    const vbsPath = getVbsPath();
    if (existsSync(vbsPath)) {
      try { unlinkSync(vbsPath); } catch { /* ignore */ }
    }

    return { ok: true };
  }

  async status(): Promise<AutostartStatus> {
    const valueName = getValueName();
    const data = await registryQuery(valueName);
    const installed = data !== null;
    return {
      installed,
      backend: 'win32',
      details: installed
        ? { registryValue: valueName, registryData: data, vbsPath: getVbsPath() }
        : { registryValue: valueName },
    };
  }
}
