import { readFileSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';

export interface ClaudeCompletionMarker {
  exitStatus: number;
  sessionId: string;
}

/** A run ID is generated by crontick; reject imported IDs that could escape runs/. */
export function claudeCompletionMarkerPath(dataDir: string, runId: string): string {
  if (!/^[A-Za-z0-9_-]+$/.test(runId)) throw new Error('Invalid run ID for Claude completion marker');
  return join(resolve(dataDir), 'runs', `${runId}.claude-hook.json`);
}

/** A hook is only useful when it recorded a real exit code for this run's session. */
export function readClaudeCompletionMarker(
  dataDir: string,
  runId: string,
  expectedSessionId: string | undefined,
  readFile: (path: string) => string = (path) => readFileSync(path, 'utf8'),
): ClaudeCompletionMarker | undefined {
  if (!expectedSessionId) return undefined;
  try {
    const value: unknown = JSON.parse(readFile(claudeCompletionMarkerPath(dataDir, runId)));
    if (typeof value !== 'object' || value === null || Array.isArray(value)) return undefined;
    const marker = value as Record<string, unknown>;
    if (marker['sessionId'] !== expectedSessionId) return undefined;
    if (!Number.isInteger(marker['exitStatus']) || (marker['exitStatus'] as number) < 0 || (marker['exitStatus'] as number) > 255) return undefined;
    return { exitStatus: marker['exitStatus'] as number, sessionId: expectedSessionId };
  } catch {
    // Missing, partial, or unreadable hooks are expected: normal result parsing
    // remains authoritative and restart recovery keeps its existing fallback.
    return undefined;
  }
}

/** Normal runs have a definitive parseResult outcome, so discard their hook. */
export function removeClaudeCompletionMarker(
  dataDir: string,
  runId: string,
  removeFile: (path: string) => void = (path) => rmSync(path, { force: true }),
): void {
  try {
    removeFile(claudeCompletionMarkerPath(dataDir, runId));
  } catch {
    // The marker never affects a normal run's status.
  }
}
